/**
 * Configuration Constants
 * All magic numbers and configuration values
 */

// API Configuration
export const MAX_RETRIES = 3;
export const RETRY_DELAYS = [2000, 4000, 8000];
export const VERTEX_SCOPE = 'https://www.googleapis.com/auth/cloud-platform';

// Image Configuration
export const MAX_REF_IMAGE_SIZE = 2560;
export const MAX_REFS = 14;

// History Configuration
export const HISTORY_PAGE_SIZE = 20;

// Queue Configuration
export const DEFAULT_QUEUE_DELAY_MS = 3000;
export const MAX_QUEUE_ITEMS = 100;
export const MAX_VARIATIONS_PER_PROMPT = 10;
export const QUEUE_STORAGE_KEY = 'queue_state';

// Generation Configuration
export const MAX_CONVERSATION_TURNS = 10;

// Zoom Configuration
export const FS_MAX_ZOOM = 10;
export const FS_MIN_ZOOM = 1;
export const IMAGE_BOX_MAX_ZOOM = 5;
export const IMAGE_BOX_MIN_ZOOM = 1;
export const DOUBLE_TAP_THRESHOLD = 300;
export const DOUBLE_TAP_ZOOM = 2.5;
export const SWIPE_THRESHOLD_Y = 80;
export const SWIPE_THRESHOLD_X = 50;
export const SWIPE_DISMISS_THRESHOLD = 100;

// Notification Sound (base64 encoded)
export const NOTIFICATION_SOUND = 'data:audio/mp3;base64,//uQxAAAAAANIAAAAAExBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7kMQOg8AAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+5LEBIPAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVQ==';

// Known Vertex AI models
export const VERTEX_MODELS = [
  'gemini-3-pro-image-preview',
  'gemini-2.5-flash-image',
  'gemini-2.0-flash-preview-image-generation',
  'gemini-2.0-flash-exp',
  'imagen-3.0-generate-002',
  'imagen-3.0-fast-generate-001'
];
